#!/usr/bin/env bash

CPUTemp=$((cat /sys/class/thermal/thermal_zone0/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/')
notify-send -t 8000 "$(
free -m | awk 'NR==2{printf "🐏 Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }'
top -bn1 | grep load | awk '{printf "🧠 Load: %.2f\n", $(NF-2)}'
printf "🌡️CPU: $CPUTemp"
)"